# Generated by Django 5.2.3 on 2025-08-09 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=200, unique=True, verbose_name='معرف الحدث')),
                ('event_type', models.CharField(max_length=50, verbose_name='نوع الحدث')),
                ('processed', models.BooleanField(default=False, verbose_name='تم المعالجة')),
                ('data', models.JSONField(verbose_name='بيانات الحدث')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'حدث Webhook',
                'verbose_name_plural': 'أحداث Webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=200, unique=True, verbose_name='معرف نية الدفع')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=200, verbose_name='معرف الشحن')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='العملة')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('processing', 'قيد المعالجة'), ('succeeded', 'نجح'), ('failed', 'فشل'), ('cancelled', 'ملغي'), ('refunded', 'مسترد')], default='pending', max_length=15, verbose_name='حالة الدفع')),
                ('stripe_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='رسوم Stripe')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المبلغ الصافي')),
                ('failure_reason', models.TextField(blank=True, verbose_name='سبب الفشل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking', verbose_name='الحجز')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
