# Generated by Django 5.2.5 on 2025-08-12 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_message'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='vodafone_cash', max_length=30, verbose_name='طريقة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='رقم المرسل')),
                ('transaction_ref', models.CharField(blank=True, max_length=60, verbose_name='رقم العملية/المرجع (اختياري)')),
                ('screenshot', models.ImageField(upload_to='manual_payments/', verbose_name='صورة إثبات الدفع')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات المشرف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payment', to='bookings.booking', verbose_name='الحجز')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_manual_payments', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
            ],
            options={
                'verbose_name': 'دفعة يدوية',
                'verbose_name_plural': 'دفعات يدوية',
                'ordering': ['-created_at'],
            },
        ),
    ]
