# Generated by Django 5.2.3 on 2025-08-14 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_apartmentimage_category'),
        ('payments', '0002_manualpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='المبلغ')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('succeeded', 'نجح'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='pending', max_length=10, verbose_name='الحالة')),
                ('stripe_session_id', models.CharField(blank=True, max_length=200, verbose_name='Stripe Session ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_accesses', to='listings.apartment', verbose_name='الشقة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_accesses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'وصول المعاينة',
                'verbose_name_plural': 'وصولات المعاينة',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'apartment', 'stripe_session_id')},
            },
        ),
    ]
