# Generated by Django 5.2.3 on 2025-08-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_viewingaccess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewingAccess',
        ),
    ]
