# Generated by Django 5.2.3 on 2025-08-09 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الموقع')),
                ('city', models.CharField(max_length=50, verbose_name='المدينة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'موقع',
                'verbose_name_plural': 'المواقع',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشقة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('main_image', models.ImageField(upload_to='apartments/main/', verbose_name='الصورة الرئيسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='listings.location', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'شقة',
                'verbose_name_plural': 'الشقق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartments/gallery/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.apartment', verbose_name='الشقة')),
            ],
            options={
                'verbose_name': 'صورة شقة',
                'verbose_name_plural': 'صور الشقق',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم/رقم الغرفة')),
                ('bed_count', models.PositiveIntegerField(verbose_name='عدد الأسرة')),
                ('room_image', models.ImageField(blank=True, upload_to='rooms/', verbose_name='صورة الغرفة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الغرفة')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='listings.apartment', verbose_name='الشقة')),
            ],
            options={
                'verbose_name': 'غرفة',
                'verbose_name_plural': 'الغرف',
                'unique_together': {('apartment', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10, verbose_name='رقم السرير')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الشهري')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('booked', 'محجوز'), ('maintenance', 'صيانة')], default='available', max_length=15, verbose_name='الحالة')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='listings.room', verbose_name='الغرفة')),
            ],
            options={
                'verbose_name': 'سرير',
                'verbose_name_plural': 'الأسرة',
                'unique_together': {('room', 'bed_number')},
            },
        ),
    ]
