# Generated by Django 5.2.3 on 2025-08-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentimage',
            name='category',
            field=models.CharField(choices=[('bathroom', 'الحمام'), ('kitchen', 'المطبخ'), ('living', 'الصالة'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='التصنيف'),
        ),
    ]
