# Generated by Django 5.2.5 on 2025-08-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_accepted',
            field=models.BooleanField(default=False, verbose_name='تمت الموافقة على العقد'),
        ),
        migrations.AddField(
            model_name='user',
            name='contract_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة على العقد'),
        ),
        migrations.AddField(
            model_name='user',
            name='contract_accepted_ip',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='IP الموافقة على العقد'),
        ),
    ]
