# Generated by Django 5.2.3 on 2025-08-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingorder_booking_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10, verbose_name='عمولة السرير'),
        ),
    ]
